### ISSUE TITLE
Launch metamask 

### ISSUE THREAD

**Issue by pociej** [golemfactory/onboarding#4]
- [x] Launch ethereum provider component  
- [x] Use metamask onboarding library 
- [x] Create network switch/add mechanism

```[tasklist]
### Tasks
- [ ] https://github.com/golemfactory/onboarding/issues/2
```
